### ISSUE TITLE
Sort out assets in Community directory

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-general#14]
Sort out large and missing assets.

No more than 150x150.

Useful tool: https://github.com/imagemin/imagemin-cli

**Comment by dadofsambonzuki** [comment]
@bubelov - Pls could you get a complete list of missing or inappropriately large community assets?

**Comment by bubelov** [comment]
@dadofsambonzuki they aren't in the DB so there is no easy way to find the missing assets. As for the large images, I think @secondl1ght has a script which is supposed to handle that

**Comment by secondl1ght** [comment]
An easy way to check for missing assets is to go to the Directory page on the site and go through each community section with the browser console open. You will see the 404 requests in there. imagemin is a good CLI tool to reduce the file size of images but it doesn't do any resizing of dimensions AFAIK. If not there is probably another tool we can use for that. Best way to do it would be pull assets locally and do the optimizing there rather than on the prod server I think. Then replace them when ready.

**Comment by dadofsambonzuki** [comment]
Automated via the netify CDN tools.
